apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-dev-traefik-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
