apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stacks.back.name" . }}
  labels:
    {{- /* - include "stacks.back.metadata.labels" . | nindent 4 */}}
    app: {{ include "stacks.back.name" . }}
    layer: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "stacks.back.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "stacks.back.name" . }}
    spec:
      containers:
      - image: {{ include "stacks.back.image.fullname" . }}
        imagePullPolicy: {{ .Values.stacks.back.image.imagePullPolicy }}
        name: {{ include "stacks.back.name" . }}
        {{- if .Values.stacks.back.image.command }}
        command: {{ toYaml .Values.stacks.back.image.command | nindent 10 }}
        {{- end }}
        {{- if .Values.stacks.back.image.args }}
        args: {{ .Values.stacks.back.image.args | toYaml | nindent 10 }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.stacks.back.image.ports.containerPort }}
        env:
          {{- if .Values.stacks.back.image.env }}
          {{- .Values.stacks.back.image.env | toYaml | nindent 10 }}
          {{- end }}
