{{- $top := . -}}
{{- $namespace := .Release.Namespace -}}
{{- range $stack, $values := $top.Values.stacks }}
---
{{- $stackName := include "stack.name" (list $top $stack) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $stackName }}
  labels:
    {{- /* - include "stacks.back.metadata.labels" . | nindent 4 */}}
    app: {{ $stackName }}
    layer: {{ include "stack.settings" (list $top $stack) }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $stackName }}
  template:
    metadata:
      labels:
        app: {{ $stackName }}
    spec:
      containers:
      - image: {{ $values.image.name }}
        imagePullPolicy: {{ $values.image.imagePullPolicy }}
        name: {{ $stackName }}
        {{- if $values.image.command }}
        command: {{ toYaml $values.image.command | nindent 10 }}
        {{- end }}
        {{- if $values.image.args }}
        args: {{ $values.image.args | toYaml | nindent 10 }}
        {{- end }}
        {{- if $values.image.ports }}
        ports:
          {{- if $values.image.ports.containerPort }}
          - containerPort: {{ $values.image.ports.containerPort }}
          {{- end }}
        {{- end }}
        {{- if $values.image.env }}
        env:
          {{- $values.image.env | toYaml | nindent 10 }}
       {{- end }}
{{- end }}
